import { useState } from "react"
const Colores = () => {
    const [color, setColor] = useState('transparent')
    const textos = ['indianred',
        'lightcoral',
        'salmon',
        'darksalmon',
        'lightsalmon',
        'crimson',
        'red',
        'firebrick',
        'darkred',
        'pink',
        'lightpink',
        'hotpink',
        'deeppink',
        'mediumvioletred',
        'palevioletred',
        'lightsalmon',
        'coral',
        'tomato',
        'orangered',
        'darkorange',
        'orange',
        'gold',
        'yellow',
        'lightyellow',
        'lemonchiffon',
        'lightgoldenrodyellow',
        'papayawhip',
        'moccasin',
        'peachpuff',
        'palegoldenrod',
        'khaki',
        'darkkhaki',
        'lavender',
        'thistle',
        'plum',
        'violet',
        'orchid',
        'fuchsia',
        'magenta',
        'mediumorchid',
        'mediumpurple',
        'rebeccapurple',
        'blueviolet',
        'darkviolet',
        'darkorchid',
        'darkmagenta',
        'purple',
        'indigo',
        'slateblue',
        'darkslateblue',
        'mediumslateblue',
        'greenyellow',
        'chartreuse',
        'lawngreen',
        'lime',
        'limegreen',
        'palegreen',
        'lightgreen',
        'mediumspringgreen',
        'springgreen',
        'mediumseagreen',
        'seagreen',
        'forestgreen',
        'green',
        'darkgreen',
        'yellowgreen',
        'olivedrab',
        'olive',
        'darkolivegreen',
        'mediumaquamarine',
        'darkseagreen',
        'lightseagreen',
        'darkcyan',
        'teal',
        'aqua',
        'cyan',
        'lightcyan',
        'paleturquoise',
        'aquamarine',
        'turquoise',
        'mediumturquoise',
        'darkturquoise',
        'cadetblue',
        'steelblue',
        'lightsteelblue',
        'powderblue',
        'lightblue',
        'skyblue',
        'lightskyblue',
        'deepskyblue',
        'dodgerblue',
        'cornflowerblue',
        'mediumslateblue',
        'royalblue',
        'blue',
        'mediumblue',
        'darkblue',
        'navy',
        'midnightblue',
        'cornsilk',
        'blanchedalmond',
        'bisque',
        'navajowhite',
        'wheat',
        'burlywood',
        'tan',
        'rosybrown',
        'sandybrown',
        'goldenrod',
        'darkgoldenrod',
        'peru',
        'chocolate',
        'saddlebrown',
        'sienna',
        'brown',
        'maroon',
        'white',
        'snow',
        'honeydew',
        'mintcream',
        'azure',
        'aliceblue',
        'ghostwhite',
        'whitesmoke',
        'seashell',
        'beige',
        'oldlace',
        'floralwhite',
        'ivory',
        'antiquewhite',
        'linen',
        'lavenderblush',
        'mistyrose',
        'gainsboro',
        'lightgray',
        'silver',
        'darkgray',
        'gray',
        'dimgray',
        'lightslategray',
        'slategray',
        'darkslategray',
        'black']
    return (
        <div className="fill">
            <div className="colorGrid">
                {textos.map((key,i) => {
                    return (
                        <button
                        id={`coloritem-${i}`} key={`coloritem-${i}`}
                            onClick={(e) => { e.preventDefault(); setColor(key); }}
                            className={`btn-color bgcolor-${key}`}></button>)
                })

                }
                <br />
                <button
                    onClick={(e) => { e.preventDefault(); setColor('transparent'); }}
                    className={`btn-color-transparent bgcolor-white`}>Transparente</button>
            </div>

            <p className={`mayusculas fontcolor-black`}>{color} </p>
        </div>

    )
}
export default Colores